fixes image and related articles
techsweave/eml-fe pull request #74
Opened 2021-07-27 16:46 UTC by nicoloGiaccone

2021-07-27 16:49 UTC, Manuv46 approved these changes

2021-07-27 16:54 UTC, Manuv46 requested changes
Fix: round the price to two decimal places after the decimal point, on CartSummary.

2021-07-28 08:21 UTC, nicoloGiaccone commented
> Fix: round the price to two decimal places after the decimal point, on Checkout.

Fixed

2021-07-28 08:25 UTC, marcobarbaresco approved these changes

2021-07-28 08:29 UTC, URBA22 approved these changes

2021-07-29 09:23 UTC, Manuv46 approved these changes

2021-07-29 15:53 UTC, amemeggio approved these changes

2021-07-29 17:01 UTC, samupd2013 approved these changes

2021-07-30 08:37 UTC, TitoScutari approved these changes

2021-07-30 08:37 UTC, merged